import { QUIZ_QUESTION_SECONDS } from "@/lib/quiz/timer";
import type { QuizQuestionRow } from "@/lib/quiz/types";

export type SeedChoice = { id: "a" | "b" | "c" | "d"; text: string; textEt: string };

export type SeedQuestion = {
  sortOrder: number;
  prompt: string;
  promptEt: string;
  choices: [SeedChoice, SeedChoice, SeedChoice, SeedChoice];
  correctId: "a" | "b" | "c" | "d";
  explanation: string;
  explanationEt: string;
  sourceLabel: string;
  sourceUrl: string;
  timerSeconds: number;
};

export const SEEDED_QUIZ_TITLE = "How Well Do You Really Know Dogs & Cats?";

export function seedQuestionToRow(question: SeedQuestion, id = `seed-${question.sortOrder}`): QuizQuestionRow {
  return {
    id,
    quizId: "seed",
    sortOrder: question.sortOrder,
    promptEn: question.prompt,
    promptEt: question.promptEt,
    choices: question.choices.map((choice) => ({
      id: choice.id,
      textEn: choice.text,
      textEt: choice.textEt,
    })),
    correctId: question.correctId,
    explanationEn: question.explanation,
    explanationEt: question.explanationEt,
    sourceLabel: question.sourceLabel,
    sourceUrl: question.sourceUrl,
    timerSeconds: QUIZ_QUESTION_SECONDS,
  };
}

export const SEEDED_QUIZ_QUESTIONS: SeedQuestion[] = [
  {
    sortOrder: 1,
    prompt: "A typical dog has about how many scent receptors, compared with a human’s roughly 6 million?",
    promptEt: "Kui palju lõhnaretseptoreid on tüüpilisel koeral, võrreldes inimese umbes 6 miljoniga?",
    choices: [
      { id: "a", text: "About 30 million", textEt: "Umbes 30 miljonit" },
      { id: "b", text: "About 300 million", textEt: "Umbes 300 miljonit" },
      { id: "c", text: "About 3 million", textEt: "Umbes 3 miljonit" },
      { id: "d", text: "About 30 billion", textEt: "Umbes 30 miljardit" },
    ],
    correctId: "b",
    explanation: "Dogs can have around 300 million olfactory receptors — one reason scent work feels almost supernatural next to our 6 million.",
    explanationEt: "Koertel võib olla umbes 300 miljonit haistmisretseptorit — üks põhjus, miks nende haistmine tundub meie 6 miljoni kõrval peaaegu üleloomulik.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/nutrition/does-your-dog-have-a-good-sense-of-smell/",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 2,
    prompt: "Which pair of colours can dogs generally tell apart most clearly?",
    promptEt: "Millist värvipaari suudavad koerad üldiselt kõige selgemini eristada?",
    choices: [
      { id: "a", text: "Red and green", textEt: "Punast ja rohelist" },
      { id: "b", text: "Blue and yellow", textEt: "Sinist ja kollast" },
      { id: "c", text: "They only see black and white", textEt: "Nad näevad ainult must-valget" },
      { id: "d", text: "The same rainbow humans see", textEt: "Sama vikerkaart, mida näevad inimesed" },
    ],
    correctId: "b",
    explanation: "Dogs are dichromatic: blues and yellows stand out. Reds and greens often look muddy, which is why the old “black and white” myth stuck.",
    explanationEt: "Koerad on dikromaadid: sinine ja kollane paistavad selgelt. Punane ja roheline jäävad sageli mudaseks — sellest ka vana müüt, et nad näevad ainult must-valget.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/health/are-dogs-color-blind/",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 3,
    prompt: "A cat can hear sounds up to roughly which frequency?",
    promptEt: "Kui kõrgeid helisid suudab kass umbes kuulda?",
    choices: [
      { id: "a", text: "20 kHz — the same as a young human", textEt: "20 kHz — sama mis noor inimene" },
      { id: "b", text: "35 kHz", textEt: "35 kHz" },
      { id: "c", text: "About 64 kHz", textEt: "Umbes 64 kHz" },
      { id: "d", text: "120 kHz", textEt: "120 kHz" },
    ],
    correctId: "c",
    explanation: "Cats hear well into the ultrasonic range (around 64 kHz), handy for hunting rodents that squeak far above our hearing.",
    explanationEt: "Kassid kuulevad hästi ultrahelivahemikku (umbes 64 kHz), mis aitab hiiri jahti pidada — nende piiksumine jääb meie kuulmisest kõrgemale.",
    sourceLabel: "VCA Animal Hospitals",
    sourceUrl: "https://vcahospitals.com/know-your-pet/cat-behavior-problems-noise-phobias-and-noise-aversion",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 4,
    prompt: "Why don’t cats usually chase sweet treats the way people do?",
    promptEt: "Miks ei torma kassid magusate maiuste järele nagu inimesed?",
    choices: [
      { id: "a", text: "They have no taste buds at all", textEt: "Neil pole üldse maitsemeeli" },
      { id: "b", text: "They lack a working sweet-taste receptor", textEt: "Neil puudub töötav magusamaitse retseptor" },
      { id: "c", text: "Sugar is instantly toxic to every cat", textEt: "Suhkur on igale kassile kohe mürgine" },
      { id: "d", text: "Their tongues are too rough to taste", textEt: "Nende keel on maitsmiseks liiga kare" },
    ],
    correctId: "b",
    explanation: "Cats have a broken sweet-taste receptor gene, so sugar doesn’t register the way it does for us. That’s biology, not pickiness.",
    explanationEt: "Kassidel on katkine magusamaitse geeni, seega suhkur ei registreeru nagu meil. See on bioloogia, mitte valivus.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/feeding-your-cat",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 5,
    prompt: "How do dogs mainly cool themselves?",
    promptEt: "Kuidas koerad peamiselt jahtuvad?",
    choices: [
      { id: "a", text: "A full-body sweat like humans", textEt: "Kogu kehaga higistades nagu inimesed" },
      { id: "b", text: "Panting, plus a little moisture through paw pads", textEt: "Hingeldades, pluss veidi niiskust käpapadjandite kaudu" },
      { id: "c", text: "Only through their ears", textEt: "Ainult kõrvade kaudu" },
      { id: "d", text: "Only by jumping in water", textEt: "Ainult vette hüpates" },
    ],
    correctId: "b",
    explanation: "Panting does most of the cooling. Paw pads have some sweat glands, but they are not a dog’s air-conditioning system.",
    explanationEt: "Hingeldamine teeb suurema osa jahutusest. Käpapadjanditel on higinäärmeid, aga see pole koera kliimaseade.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/health/do-dogs-sweat/",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 6,
    prompt: "The tapetum lucidum in a cat’s eye mainly helps by:",
    promptEt: "Kasside silmas olev tapetum lucidum aitab peamiselt:",
    choices: [
      { id: "a", text: "Making cats completely colour-blind", textEt: "Tehes kassid täiesti värvipimedaks" },
      { id: "b", text: "Reflecting light to boost night vision", textEt: "Peegeldades valgust, et parandada nägemist pimedas" },
      { id: "c", text: "Blocking ultraviolet light like sunglasses", textEt: "Blokeerides ultraviolettvalgust nagu päikeseprillid" },
      { id: "d", text: "Letting cats see infrared body heat", textEt: "Lastes kassidel näha infrapunast kehasoojust" },
    ],
    correctId: "b",
    explanation: "That mirror-like layer bounces light back through the retina — the glow you see in flash photos, and a big night-hunting advantage.",
    explanationEt: "See peegellaadne kiht põrkab valguse võrkkesta kaudu tagasi — sähvatus, mida näed välguga fotodel, ja suur eelis öisel jahil.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/feline-vision",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 7,
    prompt: "A cat’s whiskers are especially useful because they:",
    promptEt: "Kasside vurrud on eriti kasulikud, sest need:",
    choices: [
      { id: "a", text: "Are only for looking cute", textEt: "On ainult armsuse pärast" },
      { id: "b", text: "Help judge whether a gap is wide enough", textEt: "Aitavad hinnata, kas vahe on piisavalt lai" },
      { id: "c", text: "Taste sugar in the air", textEt: "Maitsvad õhus olevat suhkrut" },
      { id: "d", text: "Replace the need for hearing", textEt: "Asendavad kuulmist" },
    ],
    correctId: "b",
    explanation: "Whiskers are precision sensors. Their spread is a living ruler for “will I fit?” — which is why trimmed whiskers stress cats.",
    explanationEt: "Vurrud on täpsed andurid. Nende ulatus on elav joonlaud küsimusele „kas ma mahun?“ — seepärast teeb vurrude lõikamine kassile stressi.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/feline-behavior-problems-scratching-behavior",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 8,
    prompt: "Newborn puppies typically:",
    promptEt: "Vastsündinud kutsikad tavaliselt:",
    choices: [
      { id: "a", text: "See and hear clearly from minute one", textEt: "Näevad ja kuulevad selgelt esimesest hetkest" },
      { id: "b", text: "Cannot see or hear yet — eyes and ears stay closed", textEt: "Ei näe ega kuule veel — silmad ja kõrvad on suletud" },
      { id: "c", text: "Already have adult teeth", textEt: "Neil on juba täiskasvanud hambad" },
      { id: "d", text: "Trot after mum within minutes", textEt: "Jooksevad ema järel minutitega" },
    ],
    correctId: "b",
    explanation: "Puppies are born blind and deaf. Eyes and ear canals open over the following weeks as the nervous system catches up.",
    explanationEt: "Kutsikad sünnivad pimedate ja kurtidena. Silmad ja kuulmekäigud avanevad järgnevate nädalate jooksul, kui närvisüsteem järele jõuab.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/dog-breeding/puppy-development-stages-from-birth-to-2-years/",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 9,
    prompt: "“Dogs see only in black and white.” What’s the verdict?",
    promptEt: "„Koerad näevad ainult must-valget.“ Mis on tõde?",
    choices: [
      { id: "a", text: "True — zero colour", textEt: "Tõsi — üldse pole värve" },
      { id: "b", text: "Myth — they see some colour, especially blue and yellow", textEt: "Müüt — nad näevad mõnda värvi, eriti sinist ja kollast" },
      { id: "c", text: "True except for poodles", textEt: "Tõsi, välja arvatud puudelid" },
      { id: "d", text: "Myth — they see more colours than humans", textEt: "Müüt — nad näevad rohkem värve kui inimesed" },
    ],
    correctId: "b",
    explanation: "The black-and-white story is a classic myth. Dogs have fewer colour cones than we do, but the world is not a silent film.",
    explanationEt: "Must-valge lugu on klassikaline müüt. Koertel on vähem värvikolvikesi kui meil, aga maailm pole tummfilm.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/health/are-dogs-color-blind/",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 10,
    prompt: "A typical house cat sleeps about how long each day?",
    promptEt: "Kui kaua magab tavaline kodukass ööpäevas?",
    choices: [
      { id: "a", text: "4–6 hours", textEt: "4–6 tundi" },
      { id: "b", text: "8 hours, like many humans", textEt: "8 tundi, nagu paljud inimesed" },
      { id: "c", text: "12–16 hours", textEt: "12–16 tundi" },
      { id: "d", text: "22 hours, no exceptions", textEt: "22 tundi, eranditeta" },
    ],
    correctId: "c",
    explanation: "Cats are champion nappers: often 12–16 hours in a 24-hour stretch, in short bursts rather than one long night.",
    explanationEt: "Kassid on meistrid uinakutest: sageli 12–16 tundi 24 tunni jooksul, lühikeste tsüklitena, mitte ühe pika ööna.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/normal-sleep-behavior",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 11,
    prompt: "How far can many cats rotate each ear?",
    promptEt: "Kui palju suudavad paljud kassid kumbagi kõrva pöörata?",
    choices: [
      { id: "a", text: "About 20 degrees", textEt: "Umbes 20 kraadi" },
      { id: "b", text: "About 90 degrees", textEt: "Umbes 90 kraadi" },
      { id: "c", text: "Up to 180 degrees", textEt: "Kuni 180 kraadi" },
      { id: "d", text: "They cannot rotate ears independently", textEt: "Nad ei saa kõrvu iseseisvalt pöörata" },
    ],
    correctId: "c",
    explanation: "Independent, nearly 180° ear swivels let a cat pinpoint a rustle without turning its head — radar dishes with fur.",
    explanationEt: "Sõltumatud, peaaegu 180° kõrvapöörded lasevad kassil kahinat täpselt paikneda ilma pead keeramata — karvaga radarid.",
    sourceLabel: "Cornell University College of Veterinary Medicine",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/feline-behavior-problems-aggression",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 12,
    prompt: "About how many muscles control each cat ear?",
    promptEt: "Umbes mitu lihast juhib kumbagi kassi kõrva?",
    choices: [
      { id: "a", text: "2", textEt: "2" },
      { id: "b", text: "8", textEt: "8" },
      { id: "c", text: "32", textEt: "32" },
      { id: "d", text: "100", textEt: "100" },
    ],
    correctId: "c",
    explanation: "Roughly 32 muscles per ear give cats that satellite-dish precision. Humans manage with a handful, and most of us can’t even wiggle.",
    explanationEt: "Umbes 32 lihast kõrva kohta annab kassidele satelliitantenni täpsuse. Inimene saab hakkama käputäiega ja enamik meist ei suuda isegi kõrvu liigutada.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 13,
    prompt: "A Greyhound at a full sprint can reach about:",
    promptEt: "Täisgalopis võib hurta joosta umbes:",
    choices: [
      { id: "a", text: "20 mph (32 km/h)", textEt: "20 miili tunnis (32 km/h)" },
      { id: "b", text: "28 mph (45 km/h)", textEt: "28 miili tunnis (45 km/h)" },
      { id: "c", text: "45 mph (72 km/h)", textEt: "45 miili tunnis (72 km/h)" },
      { id: "d", text: "70 mph (113 km/h)", textEt: "70 miili tunnis (113 km/h)" },
    ],
    correctId: "c",
    explanation: "Greyhounds are built like springs: around 45 mph in a burst, among the fastest of all dog breeds.",
    explanationEt: "Hurtad on ehitatud nagu vedrud: purskes umbes 72 km/h, ühed kiireimad koeratõud.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/dog-breeds/greyhound/",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 14,
    prompt: "A healthy cat’s resting heart rate is typically:",
    promptEt: "Terve kassi puhkeoleku südame löögisagedus on tavaliselt:",
    choices: [
      { id: "a", text: "40–60 beats per minute", textEt: "40–60 lööki minutis" },
      { id: "b", text: "80–100 beats per minute", textEt: "80–100 lööki minutis" },
      { id: "c", text: "140–220 beats per minute", textEt: "140–220 lööki minutis" },
      { id: "d", text: "300–400 beats per minute", textEt: "300–400 lööki minutis" },
    ],
    correctId: "c",
    explanation: "Smaller animals run hotter clocks. A calm cat often sits in the 140–220 bpm range — alarmingly fast if you expected a human pulse.",
    explanationEt: "Väiksemad loomad käivad kiirema taktiga. Rahuliku kassi süda on sageli 140–220 lööki minutis — ehmatavalt kiire, kui ootasid inimese pulssi.",
    sourceLabel: "VCA Animal Hospitals",
    sourceUrl: "https://vcahospitals.com/know-your-pet/heart-disease-in-cats",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 15,
    prompt: "A wagging tail always means a dog is happy and wants to be petted. True?",
    promptEt: "Saba liputamine tähendab alati, et koer on õnnelik ja tahab pai. Tõsi?",
    choices: [
      { id: "a", text: "Always true", textEt: "Alati tõsi" },
      { id: "b", text: "False — wagging can mean arousal, uncertainty, or a warning", textEt: "Vale — liputamine võib tähendada erutust, ebakindlust või hoiatust" },
      { id: "c", text: "True only for puppies", textEt: "Tõsi ainult kutsikate puhul" },
      { id: "d", text: "True only for Labrador Retrievers", textEt: "Tõsi ainult labradori retriiverite puhul" },
    ],
    correctId: "b",
    explanation: "Tail language is context. A stiff, high, fast wag can be a “stay back” flag, not an invitation. Read the whole dog.",
    explanationEt: "Saba keel oleneb kontekstist. Kange, kõrge, kiire liputus võib öelda „hoia eemale“, mitte „tule lähemale“. Loe kogu koera.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/advice/dog-tail-wagging-meaning/",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 16,
    prompt: "A dog’s nose print is:",
    promptEt: "Koera ninajälg on:",
    choices: [
      { id: "a", text: "The same for every dog in a breed", textEt: "Igal sama tõu koeral ühesugune" },
      { id: "b", text: "Unique, similar to a human fingerprint", textEt: "Unikaalne, sarnane inimese sõrmejäljega" },
      { id: "c", text: "Only found on wet noses", textEt: "Ainult märjal ninal" },
      { id: "d", text: "Wiped clean and redrawn every week", textEt: "Iga nädal puhtaks pühitav ja uuesti joonistatav" },
    ],
    correctId: "b",
    explanation: "The pattern of ridges on a dog’s nose is individual — one of those “wait, really?” ID facts trainers love.",
    explanationEt: "Koera nina harjade muster on individuaalne — üks neist „oot, päriselt?“ faktidest, mida treenerid armastavad.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/lifestyle/nose-print-identification/",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 17,
    prompt: "Cats are often described as crepuscular. That means they are most active:",
    promptEt: "Kasse nimetatakse sageli videvikuloomadeks. See tähendab, et nad on kõige aktiivsemad:",
    choices: [
      { id: "a", text: "At high noon", textEt: "Keskpäeval" },
      { id: "b", text: "At dawn and dusk", textEt: "Koidikul ja ehaajal" },
      { id: "c", text: "Only in pitch darkness", textEt: "Ainult pimedas" },
      { id: "d", text: "One afternoon a week", textEt: "Kord nädalas pärastlõunal" },
    ],
    correctId: "b",
    explanation: "Dawn and dusk are prime hunting hours. That 5 a.m. zoomie is not a personal attack — it’s ancestral scheduling.",
    explanationEt: "Koidik ja eha on peamised jahi tunnid. See hommikune kella viie tormamine pole isiklik rünnak — see on esivanemate ajakava.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/play-and-predatory-behavior",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 18,
    prompt: "Compared with humans, a dog’s sense of smell is often described as:",
    promptEt: "Võrreldes inimesega kirjeldatakse koera haistmist sageli kui:",
    choices: [
      { id: "a", text: "Slightly weaker", textEt: "Veidi nõrgemat" },
      { id: "b", text: "About the same", textEt: "Umbes sama" },
      { id: "c", text: "Thousands to tens of thousands of times more sensitive", textEt: "Tuhandeid kuni kümneid tuhandeid kordi tundlikumat" },
      { id: "d", text: "Useful only for finding food", textEt: "Kasulikku ainult toidu leidmiseks" },
    ],
    correctId: "c",
    explanation: "Estimates often land between 10,000 and 100,000 times more sensitive, depending on breed — enough to detect traces we would never notice.",
    explanationEt: "Hinnangud jäävad sageli 10 000 kuni 100 000 korda tundlikumaks, olenevalt tõust — piisav, et tabada jälgi, mida meie kunagi ei märkaks.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/nutrition/does-your-dog-have-a-good-sense-of-smell/",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 19,
    prompt: "StayWithMyPet is built so that:",
    promptEt: "StayWithMyPet on loodud selleks, et:",
    choices: [
      { id: "a", text: "Only veterinary clinics can book walks", textEt: "Ainult loomakliinikud saaksid jalutuskäike broneerida" },
      { id: "b", text: "Pet Parents and Pet Friends can connect for trusted pet companionship", textEt: "Lemmikloomaomanikud ja lemmikloomasõbrad saaksid usaldusväärseks seltsiks kokku saada" },
      { id: "c", text: "Pets are listed for sale", textEt: "Lemmikloomi müüa" },
      { id: "d", text: "Only professional trainers may join", textEt: "Liituda saaksid ainult professionaalsed treenerid" },
    ],
    correctId: "b",
    explanation: "It’s a community for people who have pets and people who want to spend time with them — walks, visits, and home-based care, not a pet shop.",
    explanationEt: "See on kogukond neile, kellel on lemmikloom, ja neile, kes tahavad nendega aega veeta — jalutuskäigud, külaskäigud ja kodune hooldus, mitte lemmikloomapood.",
    sourceLabel: "StayWithMyPet",
    sourceUrl: "https://www.staywithmypet.ee/about",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
  {
    sortOrder: 20,
    prompt: "If you have a pet and want a trusted person to spend time with them, where do you start on StayWithMyPet?",
    promptEt: "Kui sul on lemmikloom ja tahad usaldusväärset inimest temaga aega veetma, kust StayWithMyPetis alustad?",
    choices: [
      { id: "a", text: "Find pets", textEt: "Leia lemmikloomi" },
      { id: "b", text: "Find care", textEt: "Leia hooldust" },
      { id: "c", text: "The admin dashboard", textEt: "Adminiliides" },
      { id: "d", text: "Pricing only", textEt: "Ainult hinnakiri" },
    ],
    correctId: "b",
    explanation: "“Find care” is the Pet Parent path. “Find pets” is for people who want to care for a pet. Same community, two doors.",
    explanationEt: "„Leia hooldust“ on lemmikloomaomaniku tee. „Leia lemmikloomi“ on neile, kes tahavad looma hooldada. Sama kogukond, kaks ust.",
    sourceLabel: "StayWithMyPet",
    sourceUrl: "https://www.staywithmypet.ee/find-care",
    timerSeconds: QUIZ_QUESTION_SECONDS,
  },
];
