export type SeedChoice = { id: "a" | "b" | "c" | "d"; text: string };

export type SeedQuestion = {
  sortOrder: number;
  prompt: string;
  choices: [SeedChoice, SeedChoice, SeedChoice, SeedChoice];
  correctId: "a" | "b" | "c" | "d";
  explanation: string;
  sourceLabel: string;
  sourceUrl: string;
  timerSeconds: number;
};

export const SEEDED_QUIZ_TITLE = "How Well Do You Really Know Dogs & Cats?";

export const SEEDED_QUIZ_QUESTIONS: SeedQuestion[] = [
  {
    sortOrder: 1,
    prompt: "A typical dog has about how many scent receptors, compared with a human’s roughly 6 million?",
    choices: [
      { id: "a", text: "About 30 million" },
      { id: "b", text: "About 300 million" },
      { id: "c", text: "About 3 million" },
      { id: "d", text: "About 30 billion" },
    ],
    correctId: "b",
    explanation: "Dogs can have around 300 million olfactory receptors — one reason scent work feels almost supernatural next to our 6 million.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/nutrition/does-your-dog-have-a-good-sense-of-smell/",
    timerSeconds: 15,
  },
  {
    sortOrder: 2,
    prompt: "Which pair of colours can dogs generally tell apart most clearly?",
    choices: [
      { id: "a", text: "Red and green" },
      { id: "b", text: "Blue and yellow" },
      { id: "c", text: "They only see black and white" },
      { id: "d", text: "The same rainbow humans see" },
    ],
    correctId: "b",
    explanation: "Dogs are dichromatic: blues and yellows stand out. Reds and greens often look muddy, which is why the old “black and white” myth stuck.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/health/are-dogs-color-blind/",
    timerSeconds: 15,
  },
  {
    sortOrder: 3,
    prompt: "A cat can hear sounds up to roughly which frequency?",
    choices: [
      { id: "a", text: "20 kHz — the same as a young human" },
      { id: "b", text: "35 kHz" },
      { id: "c", text: "About 64 kHz" },
      { id: "d", text: "120 kHz" },
    ],
    correctId: "c",
    explanation: "Cats hear well into the ultrasonic range (around 64 kHz), handy for hunting rodents that squeak far above our hearing.",
    sourceLabel: "VCA Animal Hospitals",
    sourceUrl: "https://vcahospitals.com/know-your-pet/cat-behavior-problems-noise-phobias-and-noise-aversion",
    timerSeconds: 15,
  },
  {
    sortOrder: 4,
    prompt: "Why don’t cats usually chase sweet treats the way people do?",
    choices: [
      { id: "a", text: "They have no taste buds at all" },
      { id: "b", text: "They lack a working sweet-taste receptor" },
      { id: "c", text: "Sugar is instantly toxic to every cat" },
      { id: "d", text: "Their tongues are too rough to taste" },
    ],
    correctId: "b",
    explanation: "Cats have a broken sweet-taste receptor gene, so sugar doesn’t register the way it does for us. That’s biology, not pickiness.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/feeding-your-cat",
    timerSeconds: 15,
  },
  {
    sortOrder: 5,
    prompt: "How do dogs mainly cool themselves?",
    choices: [
      { id: "a", text: "A full-body sweat like humans" },
      { id: "b", text: "Panting, plus a little moisture through paw pads" },
      { id: "c", text: "Only through their ears" },
      { id: "d", text: "Only by jumping in water" },
    ],
    correctId: "b",
    explanation: "Panting does most of the cooling. Paw pads have some sweat glands, but they are not a dog’s air-conditioning system.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/health/do-dogs-sweat/",
    timerSeconds: 15,
  },
  {
    sortOrder: 6,
    prompt: "The tapetum lucidum in a cat’s eye mainly helps by:",
    choices: [
      { id: "a", text: "Making cats completely colour-blind" },
      { id: "b", text: "Reflecting light to boost night vision" },
      { id: "c", text: "Blocking ultraviolet light like sunglasses" },
      { id: "d", text: "Letting cats see infrared body heat" },
    ],
    correctId: "b",
    explanation: "That mirror-like layer bounces light back through the retina — the glow you see in flash photos, and a big night-hunting advantage.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/feline-vision",
    timerSeconds: 15,
  },
  {
    sortOrder: 7,
    prompt: "A cat’s whiskers are especially useful because they:",
    choices: [
      { id: "a", text: "Are only for looking cute" },
      { id: "b", text: "Help judge whether a gap is wide enough" },
      { id: "c", text: "Taste sugar in the air" },
      { id: "d", text: "Replace the need for hearing" },
    ],
    correctId: "b",
    explanation: "Whiskers are precision sensors. Their spread is a living ruler for “will I fit?” — which is why trimmed whiskers stress cats.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/feline-behavior-problems-scratching-behavior",
    timerSeconds: 15,
  },
  {
    sortOrder: 8,
    prompt: "Newborn puppies typically:",
    choices: [
      { id: "a", text: "See and hear clearly from minute one" },
      { id: "b", text: "Cannot see or hear yet — eyes and ears stay closed" },
      { id: "c", text: "Already have adult teeth" },
      { id: "d", text: "Trot after mum within minutes" },
    ],
    correctId: "b",
    explanation: "Puppies are born blind and deaf. Eyes and ear canals open over the following weeks as the nervous system catches up.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/dog-breeding/puppy-development-stages-from-birth-to-2-years/",
    timerSeconds: 15,
  },
  {
    sortOrder: 9,
    prompt: "“Dogs see only in black and white.” What’s the verdict?",
    choices: [
      { id: "a", text: "True — zero colour" },
      { id: "b", text: "Myth — they see some colour, especially blue and yellow" },
      { id: "c", text: "True except for poodles" },
      { id: "d", text: "Myth — they see more colours than humans" },
    ],
    correctId: "b",
    explanation: "The black-and-white story is a classic myth. Dogs have fewer colour cones than we do, but the world is not a silent film.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/health/are-dogs-color-blind/",
    timerSeconds: 15,
  },
  {
    sortOrder: 10,
    prompt: "A typical house cat sleeps about how long each day?",
    choices: [
      { id: "a", text: "4–6 hours" },
      { id: "b", text: "8 hours, like many humans" },
      { id: "c", text: "12–16 hours" },
      { id: "d", text: "22 hours, no exceptions" },
    ],
    correctId: "c",
    explanation: "Cats are champion nappers: often 12–16 hours in a 24-hour stretch, in short bursts rather than one long night.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/normal-sleep-behavior",
    timerSeconds: 15,
  },
  {
    sortOrder: 11,
    prompt: "How far can many cats rotate each ear?",
    choices: [
      { id: "a", text: "About 20 degrees" },
      { id: "b", text: "About 90 degrees" },
      { id: "c", text: "Up to 180 degrees" },
      { id: "d", text: "They cannot rotate ears independently" },
    ],
    correctId: "c",
    explanation: "Independent, nearly 180° ear swivels let a cat pinpoint a rustle without turning its head — radar dishes with fur.",
    sourceLabel: "Cornell University College of Veterinary Medicine",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/feline-behavior-problems-aggression",
    timerSeconds: 15,
  },
  {
    sortOrder: 12,
    prompt: "About how many muscles control each cat ear?",
    choices: [
      { id: "a", text: "2" },
      { id: "b", text: "8" },
      { id: "c", text: "32" },
      { id: "d", text: "100" },
    ],
    correctId: "c",
    explanation: "Roughly 32 muscles per ear give cats that satellite-dish precision. Humans manage with a handful, and most of us can’t even wiggle.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center",
    timerSeconds: 15,
  },
  {
    sortOrder: 13,
    prompt: "A Greyhound at a full sprint can reach about:",
    choices: [
      { id: "a", text: "20 mph (32 km/h)" },
      { id: "b", text: "28 mph (45 km/h)" },
      { id: "c", text: "45 mph (72 km/h)" },
      { id: "d", text: "70 mph (113 km/h)" },
    ],
    correctId: "c",
    explanation: "Greyhounds are built like springs: around 45 mph in a burst, among the fastest of all dog breeds.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/dog-breeds/greyhound/",
    timerSeconds: 15,
  },
  {
    sortOrder: 14,
    prompt: "A healthy cat’s resting heart rate is typically:",
    choices: [
      { id: "a", text: "40–60 beats per minute" },
      { id: "b", text: "80–100 beats per minute" },
      { id: "c", text: "140–220 beats per minute" },
      { id: "d", text: "300–400 beats per minute" },
    ],
    correctId: "c",
    explanation: "Smaller animals run hotter clocks. A calm cat often sits in the 140–220 bpm range — alarmingly fast if you expected a human pulse.",
    sourceLabel: "VCA Animal Hospitals",
    sourceUrl: "https://vcahospitals.com/know-your-pet/heart-disease-in-cats",
    timerSeconds: 15,
  },
  {
    sortOrder: 15,
    prompt: "A wagging tail always means a dog is happy and wants to be petted. True?",
    choices: [
      { id: "a", text: "Always true" },
      { id: "b", text: "False — wagging can mean arousal, uncertainty, or a warning" },
      { id: "c", text: "True only for puppies" },
      { id: "d", text: "True only for Labrador Retrievers" },
    ],
    correctId: "b",
    explanation: "Tail language is context. A stiff, high, fast wag can be a “stay back” flag, not an invitation. Read the whole dog.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/advice/dog-tail-wagging-meaning/",
    timerSeconds: 15,
  },
  {
    sortOrder: 16,
    prompt: "A dog’s nose print is:",
    choices: [
      { id: "a", text: "The same for every dog in a breed" },
      { id: "b", text: "Unique, similar to a human fingerprint" },
      { id: "c", text: "Only found on wet noses" },
      { id: "d", text: "Wiped clean and redrawn every week" },
    ],
    correctId: "b",
    explanation: "The pattern of ridges on a dog’s nose is individual — one of those “wait, really?” ID facts trainers love.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/lifestyle/nose-print-identification/",
    timerSeconds: 15,
  },
  {
    sortOrder: 17,
    prompt: "Cats are often described as crepuscular. That means they are most active:",
    choices: [
      { id: "a", text: "At high noon" },
      { id: "b", text: "At dawn and dusk" },
      { id: "c", text: "Only in pitch darkness" },
      { id: "d", text: "One afternoon a week" },
    ],
    correctId: "b",
    explanation: "Dawn and dusk are prime hunting hours. That 5 a.m. zoomie is not a personal attack — it’s ancestral scheduling.",
    sourceLabel: "Cornell Feline Health Center",
    sourceUrl: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center/health-information/feline-health-topics/play-and-predatory-behavior",
    timerSeconds: 15,
  },
  {
    sortOrder: 18,
    prompt: "Compared with humans, a dog’s sense of smell is often described as:",
    choices: [
      { id: "a", text: "Slightly weaker" },
      { id: "b", text: "About the same" },
      { id: "c", text: "Thousands to tens of thousands of times more sensitive" },
      { id: "d", text: "Useful only for finding food" },
    ],
    correctId: "c",
    explanation: "Estimates often land between 10,000 and 100,000 times more sensitive, depending on breed — enough to detect traces we would never notice.",
    sourceLabel: "American Kennel Club",
    sourceUrl: "https://www.akc.org/expert-advice/nutrition/does-your-dog-have-a-good-sense-of-smell/",
    timerSeconds: 15,
  },
  {
    sortOrder: 19,
    prompt: "StayWithMyPet is built so that:",
    choices: [
      { id: "a", text: "Only veterinary clinics can book walks" },
      { id: "b", text: "Pet Parents and Pet Friends can connect for trusted pet companionship" },
      { id: "c", text: "Pets are listed for sale" },
      { id: "d", text: "Only professional trainers may join" },
    ],
    correctId: "b",
    explanation: "It’s a community for people who have pets and people who want to spend time with them — walks, visits, and home-based care, not a pet shop.",
    sourceLabel: "StayWithMyPet",
    sourceUrl: "https://www.staywithmypet.ee/about",
    timerSeconds: 15,
  },
  {
    sortOrder: 20,
    prompt: "If you have a pet and want a trusted person to spend time with them, where do you start on StayWithMyPet?",
    choices: [
      { id: "a", text: "Find pets" },
      { id: "b", text: "Find care" },
      { id: "c", text: "The admin dashboard" },
      { id: "d", text: "Pricing only" },
    ],
    correctId: "b",
    explanation: "“Find care” is the Pet Parent path. “Find pets” is for people who want to care for a pet. Same community, two doors.",
    sourceLabel: "StayWithMyPet",
    sourceUrl: "https://www.staywithmypet.ee/find-care",
    timerSeconds: 15,
  },
];
